server:
  port: 8083
  servlet:
    context-path: /notification
spring:
  application:
    name: school-notification-service
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/school-management
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
